// Mocks generated by Mockito 5.4.6 from annotations
// in apt_doc_scanner/test/document_scanner_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:apt_doc_scanner/data/sources/sync_service.dart' as _i5;
import 'package:apt_doc_scanner/domain/models/document.dart' as _i4;
import 'package:apt_doc_scanner/domain/repositories/document_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRepository extends _i1.Mock
    implements _i2.DocumentRepository {
  MockDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Document>> getAllDocuments() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDocuments, []),
            returnValue: _i3.Future<List<_i4.Document>>.value(<_i4.Document>[]),
          )
          as _i3.Future<List<_i4.Document>>);

  @override
  _i3.Future<void> saveDocument(_i4.Document? document) =>
      (super.noSuchMethod(
            Invocation.method(#saveDocument, [document]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocument(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateDocument(_i4.Document? document) =>
      (super.noSuchMethod(
            Invocation.method(#updateDocument, [document]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i5.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Document?> syncDocument(
    _i4.Document? document,
    _i5.SyncProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#syncDocument, [document, provider]),
            returnValue: _i3.Future<_i4.Document?>.value(),
          )
          as _i3.Future<_i4.Document?>);
}
